services:
  db:
    container_name: ponder-db
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder_password
      POSTGRES_DB: ponder_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ponder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponder -d ponder_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  ponder:
    container_name: ponder-app
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/init-db.sh
    environment:
      PONDER_DATABASE_URL: ${DATABASE_URL}
      PONDER_RPC_URL_10143: ${PONDER_RPC_URL_10143}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA:-ponder}
      NODE_ENV: production
      PONDER_TELEMETRY_DISABLED: true

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "42069:42069"
    networks:
      - ponder-network
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:42069/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
  node_modules:
networks:
  ponder-network:
